name: capstone_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^3.1.2
  path_provider: ^2.0.11
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.8.5
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.4
  uuid: ^4.0.0
  fl_chart: ^0.64.0
  intl: ^0.18.1
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fish.png
    - assets/hook.png
    - assets/sparkle.png
    - assets/totoro_forest.png
    - assets/ghibli_cloud.png
