import 'package:flutter/material.dart';

enum TodoCategory {
  work,
  personal,
  shopping,
  health,
  travel,
  finance,
  education,
  entertainment,
  home,
  fitness,
  hobbies,
  family,
  friends,
  selfCare,
  spirituality,
  community,
  volunteering,
  pets,
  technology,
  fashion,
  food,
  sports,
  music,
  art,
  books,
  movies,
  games,
  photography,
  gardening,
  crafts,
  writing,
  cooking,
  homeImprovement,
  other,
}

final stringToCategory = {
  'Work': TodoCategory.work,
  'Personal': TodoCategory.personal,
  'Shopping': TodoCategory.shopping,
  'Health': TodoCategory.health,
  'Travel': TodoCategory.travel,
  'Finance': TodoCategory.finance,
  'Education': TodoCategory.education,
  'Entertainment': TodoCategory.entertainment,
  'Home': TodoCategory.home,
  'Fitness': TodoCategory.fitness,
  'Hobbies': TodoCategory.hobbies,
  'Family': TodoCategory.family,
  'Friends': TodoCategory.friends,
  'Self Care': TodoCategory.selfCare,
  'Spirituality': TodoCategory.spirituality,
  'Community': TodoCategory.community,
  'Volunteering': TodoCategory.volunteering,
  'Pets': TodoCategory.pets,
  'Technology': TodoCategory.technology,
  'Fashion': TodoCategory.fashion,
  'Food': TodoCategory.food,
  'Sports': TodoCategory.sports,
  'Music': TodoCategory.music,
  'Art': TodoCategory.art,
  'Books': TodoCategory.books,
  'Movies': TodoCategory.movies,
  'Games': TodoCategory.games,
  'Photography': TodoCategory.photography,
  'Gardening': TodoCategory.gardening,
  'Crafts': TodoCategory.crafts,
  'Writing': TodoCategory.writing,
  'Cooking': TodoCategory.cooking,
  'Home Improvement': TodoCategory.homeImprovement,
};

final categoryToString = {
  TodoCategory.work: 'Work',
  TodoCategory.personal: 'Personal',
  TodoCategory.shopping: 'Shopping',
  TodoCategory.health: 'Health',
  TodoCategory.travel: 'Travel',
  TodoCategory.finance: 'Finance',
  TodoCategory.education: 'Education',
  TodoCategory.entertainment: 'Entertainment',
  TodoCategory.home: 'Home',
  TodoCategory.fitness: 'Fitness',
  TodoCategory.hobbies: 'Hobbies',
  TodoCategory.family: 'Family',
  TodoCategory.friends: 'Friends',
  TodoCategory.selfCare: 'Self Care',
  TodoCategory.spirituality: 'Spirituality',
  TodoCategory.community: 'Community',
  TodoCategory.volunteering: 'Volunteering',
  TodoCategory.pets: 'Pets',
  TodoCategory.technology: 'Technology',
  TodoCategory.fashion: 'Fashion',
  TodoCategory.food: 'Food',
  TodoCategory.sports: 'Sports',
  TodoCategory.music: 'Music',
  TodoCategory.art: 'Art',
  TodoCategory.books: 'Books',
  TodoCategory.movies: 'Movies',
  TodoCategory.games: 'Games',
  TodoCategory.photography: 'Photography',
  TodoCategory.gardening: 'Gardening',
  TodoCategory.crafts: 'Crafts',
  TodoCategory.writing: 'Writing',
  TodoCategory.cooking: 'Cooking',
  TodoCategory.homeImprovement: 'Home Improvement',
};

final categoryToIcon = {
  TodoCategory.work: Icons.work,
  TodoCategory.personal: Icons.person,
  TodoCategory.shopping: Icons.shopping_cart,
  TodoCategory.health: Icons.health_and_safety,
  TodoCategory.travel: Icons.travel_explore,
  TodoCategory.finance: Icons.monetization_on,
  TodoCategory.education: Icons.school,
  TodoCategory.entertainment: Icons.movie,
  TodoCategory.home: Icons.home,
  TodoCategory.fitness: Icons.fitness_center,
  TodoCategory.hobbies: Icons.hiking_rounded,
  TodoCategory.family: Icons.family_restroom,
  TodoCategory.friends: Icons.group,
  TodoCategory.selfCare: Icons.self_improvement,
  TodoCategory.spirituality: Icons.church,
  TodoCategory.community: Icons.people_alt,
  TodoCategory.volunteering: Icons.volunteer_activism,
  TodoCategory.pets: Icons.pets,
  TodoCategory.technology: Icons.computer,
  TodoCategory.fashion: Icons.checkroom,
  TodoCategory.food: Icons.fastfood,
  TodoCategory.sports: Icons.sports_baseball,
  TodoCategory.music: Icons.music_note,
  TodoCategory.art: Icons.brush,
  TodoCategory.books: Icons.book,
  TodoCategory.movies: Icons.movie_creation_outlined,
  TodoCategory.games: Icons.videogame_asset_outlined,
  TodoCategory.photography: Icons.photo_camera_back_outlined,
  TodoCategory.gardening: Icons.grass_outlined,
  TodoCategory.crafts: Icons.art_track_outlined,
  TodoCategory.writing: Icons.create_outlined,
  TodoCategory.cooking: Icons.kitchen_outlined,
  TodoCategory.homeImprovement: Icons.build_circle_outlined,
  TodoCategory.other: Icons.category,
};

class Todo {
  int todoId;
  String content;
  bool completed;
  bool recurrent;
  TodoCategory category;
  Map<String, dynamic>? json;

  Todo({
    required this.todoId,
    required this.content,
    required this.completed,
    required this.category,
    this.recurrent = false,
  }) {
    json = {
      'todoId': todoId,
      'content': content,
      'completed': completed,
      'category': categoryToString[category],
      'recurrent': recurrent,
    };
  }
}
