// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwoBFgTdsPciKvuq_a42dh0x41LXZBzNs',
    appId: '1:886805275939:web:88cc8f7f32b7e827b49896',
    messagingSenderId: '886805275939',
    projectId: 'perfectly-plump-plums-1c47d',
    authDomain: 'perfectly-plump-plums-1c47d.firebaseapp.com',
    storageBucket: 'perfectly-plump-plums-1c47d.firebasestorage.app',
    measurementId: 'G-79TCFR78RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIoiRmXFm8OzMv_eba9o5-UoEB9vvxEI',
    appId: '1:886805275939:android:20c0a136692f996cb49896',
    messagingSenderId: '886805275939',
    projectId: 'perfectly-plump-plums-1c47d',
    storageBucket: 'perfectly-plump-plums-1c47d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqi9TgatXGkeADw1eEQv7W0_Y8t0ZuY6g',
    appId: '1:886805275939:ios:6bc49dc8c794cf24b49896',
    messagingSenderId: '886805275939',
    projectId: 'perfectly-plump-plums-1c47d',
    storageBucket: 'perfectly-plump-plums-1c47d.firebasestorage.app',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqi9TgatXGkeADw1eEQv7W0_Y8t0ZuY6g',
    appId: '1:886805275939:ios:6bc49dc8c794cf24b49896',
    messagingSenderId: '886805275939',
    projectId: 'perfectly-plump-plums-1c47d',
    storageBucket: 'perfectly-plump-plums-1c47d.firebasestorage.app',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwoBFgTdsPciKvuq_a42dh0x41LXZBzNs',
    appId: '1:886805275939:web:2636d0983b9355c5b49896',
    messagingSenderId: '886805275939',
    projectId: 'perfectly-plump-plums-1c47d',
    authDomain: 'perfectly-plump-plums-1c47d.firebaseapp.com',
    storageBucket: 'perfectly-plump-plums-1c47d.firebasestorage.app',
    measurementId: 'G-FVVV1Q93XJ',
  );
}